from typing import List
from src.scrapers.models import PromoItem

DEMO_PROMOS: List[PromoItem] = [
    PromoItem(
        store_id="colruyt",
        external_id="colruyt_cheese_2plus2",
        title="Jong Belegen Gouda Sneden 500g",
        description="Heerlijke authentieke Belgische kaas in handige hersluitbare verpakking. Rode Prijzen actie!",
        original_price=11.98,
        promo_price=5.99,
        discount_text="2 + 2 GRATIS",
        unit_info="4 x 500 g",
        image_url="https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&auto=format&fit=crop&q=80",
        deal_url="https://www.colruyt.be/nl/acties",
        category_id="dairy_cheese",
        valid_from="2026-09-14",
        valid_until="2026-09-21",
    ),
    PromoItem(
        store_id="colruyt",
        external_id="colruyt_jupiler_crate",
        title="Jupiler Pils Bak 24 x 25cl",
        description="Het favoriete Belgische pilsbier. Exclusieve korting bij aankoop van 2 bakken.",
        original_price=33.80,
        promo_price=22.60,
        discount_text="-33% BIJ 2 BAKKEN",
        unit_info="2 x 24 x 25 cl",
        image_url="https://images.unsplash.com/photo-1608270119225-b46187db1855?w=600&auto=format&fit=crop&q=80",
        deal_url="https://www.colruyt.be/nl/acties",
        category_id="drinks",
        valid_from="2026-09-14",
        valid_until="2026-09-28",
    ),
    PromoItem(
        store_id="carrefour",
        external_id="carrefour_strawberries_be",
        title="Belgische Aardbeien Hoogstraten 500g",
        description="Zoete, sappige aardbeien van lokale Belgische telers. Carrefour Bonus Card voordeel.",
        original_price=7.98,
        promo_price=3.99,
        discount_text="1 + 1 GRATIS",
        unit_info="2 x 500 g",
        image_url="https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600&auto=format&fit=crop&q=80",
        deal_url="https://www.carrefour.be/nl/promoties",
        category_id="fruits_veg",
        valid_from="2026-09-14",
        valid_until="2026-09-20",
    ),
    PromoItem(
        store_id="delhaize",
        external_id="delhaize_croissant_breakfast",
        title="Verse Boter Croissants & Chocoladebroodjes",
        description="Dagvers gebakken in onze bakkerij met 100% echte roomboter.",
        original_price=4.80,
        promo_price=3.20,
        discount_text="3 + 1 GRATIS",
        unit_info="4 stuks",
        image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80",
        deal_url="https://www.delhaize.be/nl-be/promotions",
        category_id="bakery",
        valid_from="2026-09-14",
        valid_until="2026-09-22",
    ),
    PromoItem(
        store_id="delhaize",
        external_id="delhaize_salmon_fresh",
        title="Noorse Zalmfilet ASC met vel 4 stuks",
        description="Rijk aan omega 3 vetzuren. Verantwoord gekweekt, supervers op ijs.",
        original_price=16.99,
        promo_price=11.89,
        discount_text="-30% KORTING",
        unit_info="ca. 600 g",
        image_url="https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80",
        deal_url="https://www.delhaize.be/nl-be/promotions",
        category_id="meat_fish",
        valid_from="2026-09-14",
        valid_until="2026-09-20",
    ),
    PromoItem(
        store_id="aldi",
        external_id="aldi_wine_alberone",
        title="Witte Wijn 'Grande Alberone'",
        description="Elegante Italiaanse witte wijn met toetsen van wit fruit en citrus. Heerlijk bij vis en pasta.",
        original_price=10.98,
        promo_price=9.99,
        discount_text="2 VOOR €9.99",
        unit_info="2 x 75 cl",
        image_url="https://s7g10.scene7.com/is/image/aldinord/1077.0.witte-wijn-grande-alberone.all_belu.2026.cw38-w",
        deal_url="https://www.aldi.be/nl/aanbiedingen.html",
        category_id="drinks",
        valid_from="2026-09-16",
        valid_until="2026-09-23",
    ),
    PromoItem(
        store_id="lidl",
        external_id="lidl_bio_greek_yogurt",
        title="Milbona Bio Griekse Yoghurt 10% vet",
        description="Romige biologische yoghurt, rijk van smaak. Ideaal met honing en walnoten.",
        original_price=3.49,
        promo_price=2.29,
        discount_text="-35% MET LIDL PLUS",
        unit_info="1 kg emmer",
        image_url="https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80",
        deal_url="https://www.lidl.be/nl/acties",
        category_id="bio_organic",
        valid_from="2026-09-14",
        valid_until="2026-09-21",
    ),
    PromoItem(
        store_id="albert_heijn",
        external_id="ah_bonus_chips",
        title="Lay's & Doritos Partypack Chips",
        description="Alle varianten van Lay's Sensations, Bugles en Doritos nacho chips in de Bonus.",
        original_price=5.58,
        promo_price=2.79,
        discount_text="1 + 1 GRATIS",
        unit_info="2 zakken naar keuze",
        image_url="https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&auto=format&fit=crop&q=80",
        deal_url="https://www.ah.be/bonus",
        category_id="snacks_sweets",
        valid_from="2026-09-14",
        valid_until="2026-09-21",
    ),
    PromoItem(
        store_id="jumbo",
        external_id="jumbo_wash_ariel",
        title="Ariel All-in-1 Pods Wasmiddel 60 stuks",
        description="Onberispelijke vlekverwijdering zelfs in koud water. Kleurbescherming.",
        original_price=28.99,
        promo_price=14.49,
        discount_text="-50% 2e HALVE PRIJS",
        unit_info="60 wasbeurten",
        image_url="https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&auto=format&fit=crop&q=80",
        deal_url="https://www.jumbo.com/nl-be/aanbiedingen",
        category_id="household",
        valid_from="2026-09-14",
        valid_until="2026-09-28",
    ),
    PromoItem(
        store_id="spar",
        external_id="spar_pampers_care",
        title="Pampers Baby-Dry Luierbroekjes Jumbo Pack",
        description="Tot 12 uur bescherming tegen lekken. Dermatologisch getest.",
        original_price=34.99,
        promo_price=24.49,
        discount_text="-30% KORTING",
        unit_info="Maat 4 / 5 / 6",
        image_url="https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&auto=format&fit=crop&q=80",
        deal_url="https://www.sparretail.be/acties",
        category_id="care_baby",
        valid_from="2026-09-14",
        valid_until="2026-09-25",
    ),
    PromoItem(
        store_id="intermarche",
        external_id="intermarche_poulet_fermier",
        title="Belgische Braadkip & Kipschnitzels",
        description="Lokaal Belgisch gevogelte met kwaliteitslabel. Ideaal voor het hele gezin.",
        original_price=12.50,
        promo_price=8.75,
        discount_text="-30% IMMÉDIAT",
        unit_info="ca. 1.2 kg",
        image_url="https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&auto=format&fit=crop&q=80",
        deal_url="https://www.intermarche.be/promotions",
        category_id="meat_fish",
        valid_from="2026-09-14",
        valid_until="2026-09-21",
    ),
]
